'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="NWSproj1")>  _
Partial Public Class DataClassesDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "Extensibility Method Definitions"
  Partial Private Sub OnCreated()
  End Sub
  Partial Private Sub InsertUser(instance As User)
    End Sub
  Partial Private Sub UpdateUser(instance As User)
    End Sub
  Partial Private Sub DeleteUser(instance As User)
    End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.System.Configuration.ConfigurationManager.ConnectionStrings("NWSproj1ConnectionString").ConnectionString, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public ReadOnly Property Users() As System.Data.Linq.Table(Of User)
		Get
			Return Me.GetTable(Of User)
		End Get
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.Users")>  _
Partial Public Class User
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _ID As Integer
	
	Private _FName As String
	
	Private _LName As String
	
	Private _Mobile As String
	
	Private _Email As String
	
	Private _Password As String
	
	Private _isAdmin As System.Nullable(Of Boolean)
	
	Private _CDate As System.Nullable(Of Date)
	
	Private _MDate As System.Nullable(Of Date)
	
	Private _UID As String
	
	Private _isDel As System.Nullable(Of Boolean)
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnIDChanging(value As Integer)
    End Sub
    Partial Private Sub OnIDChanged()
    End Sub
    Partial Private Sub OnFNameChanging(value As String)
    End Sub
    Partial Private Sub OnFNameChanged()
    End Sub
    Partial Private Sub OnLNameChanging(value As String)
    End Sub
    Partial Private Sub OnLNameChanged()
    End Sub
    Partial Private Sub OnMobileChanging(value As String)
    End Sub
    Partial Private Sub OnMobileChanged()
    End Sub
    Partial Private Sub OnEmailChanging(value As String)
    End Sub
    Partial Private Sub OnEmailChanged()
    End Sub
    Partial Private Sub OnPasswordChanging(value As String)
    End Sub
    Partial Private Sub OnPasswordChanged()
    End Sub
    Partial Private Sub OnisAdminChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub OnisAdminChanged()
    End Sub
    Partial Private Sub OnCDateChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnCDateChanged()
    End Sub
    Partial Private Sub OnMDateChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnMDateChanged()
    End Sub
    Partial Private Sub OnUIDChanging(value As String)
    End Sub
    Partial Private Sub OnUIDChanged()
    End Sub
    Partial Private Sub OnisDelChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub OnisDelChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ID", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property ID() As Integer
		Get
			Return Me._ID
		End Get
		Set
			If ((Me._ID = value)  _
						= false) Then
				Me.OnIDChanging(value)
				Me.SendPropertyChanging
				Me._ID = value
				Me.SendPropertyChanged("ID")
				Me.OnIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FName", DbType:="NVarChar(500)")>  _
	Public Property FName() As String
		Get
			Return Me._FName
		End Get
		Set
			If (String.Equals(Me._FName, value) = false) Then
				Me.OnFNameChanging(value)
				Me.SendPropertyChanging
				Me._FName = value
				Me.SendPropertyChanged("FName")
				Me.OnFNameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_LName", DbType:="NVarChar(500)")>  _
	Public Property LName() As String
		Get
			Return Me._LName
		End Get
		Set
			If (String.Equals(Me._LName, value) = false) Then
				Me.OnLNameChanging(value)
				Me.SendPropertyChanging
				Me._LName = value
				Me.SendPropertyChanged("LName")
				Me.OnLNameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Mobile", DbType:="NVarChar(100)")>  _
	Public Property Mobile() As String
		Get
			Return Me._Mobile
		End Get
		Set
			If (String.Equals(Me._Mobile, value) = false) Then
				Me.OnMobileChanging(value)
				Me.SendPropertyChanging
				Me._Mobile = value
				Me.SendPropertyChanged("Mobile")
				Me.OnMobileChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Email", DbType:="NVarChar(500)")>  _
	Public Property Email() As String
		Get
			Return Me._Email
		End Get
		Set
			If (String.Equals(Me._Email, value) = false) Then
				Me.OnEmailChanging(value)
				Me.SendPropertyChanging
				Me._Email = value
				Me.SendPropertyChanged("Email")
				Me.OnEmailChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Password", DbType:="NVarChar(500)")>  _
	Public Property Password() As String
		Get
			Return Me._Password
		End Get
		Set
			If (String.Equals(Me._Password, value) = false) Then
				Me.OnPasswordChanging(value)
				Me.SendPropertyChanging
				Me._Password = value
				Me.SendPropertyChanged("Password")
				Me.OnPasswordChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_isAdmin", DbType:="Bit")>  _
	Public Property isAdmin() As System.Nullable(Of Boolean)
		Get
			Return Me._isAdmin
		End Get
		Set
			If (Me._isAdmin.Equals(value) = false) Then
				Me.OnisAdminChanging(value)
				Me.SendPropertyChanging
				Me._isAdmin = value
				Me.SendPropertyChanged("isAdmin")
				Me.OnisAdminChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Name:="CDate", Storage:="_CDate", DbType:="SmallDateTime")>  _
	Public Property [CDate]() As System.Nullable(Of Date)
		Get
			Return Me._CDate
		End Get
		Set
			If (Me._CDate.Equals(value) = false) Then
				Me.OnCDateChanging(value)
				Me.SendPropertyChanging
				Me._CDate = value
				Me.SendPropertyChanged("[CDate]")
				Me.OnCDateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_MDate", DbType:="SmallDateTime")>  _
	Public Property MDate() As System.Nullable(Of Date)
		Get
			Return Me._MDate
		End Get
		Set
			If (Me._MDate.Equals(value) = false) Then
				Me.OnMDateChanging(value)
				Me.SendPropertyChanging
				Me._MDate = value
				Me.SendPropertyChanged("MDate")
				Me.OnMDateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_UID", DbType:="VarChar(255)")>  _
	Public Property UID() As String
		Get
			Return Me._UID
		End Get
		Set
			If (String.Equals(Me._UID, value) = false) Then
				Me.OnUIDChanging(value)
				Me.SendPropertyChanging
				Me._UID = value
				Me.SendPropertyChanged("UID")
				Me.OnUIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_isDel", DbType:="Bit")>  _
	Public Property isDel() As System.Nullable(Of Boolean)
		Get
			Return Me._isDel
		End Get
		Set
			If (Me._isDel.Equals(value) = false) Then
				Me.OnisDelChanging(value)
				Me.SendPropertyChanging
				Me._isDel = value
				Me.SendPropertyChanged("isDel")
				Me.OnisDelChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class
